version: '3.8'

volumes:
  mongodb_data:
    driver: local

services:
  api:
    build:
      target: base
    container_name: api
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - /usr/src/app/node_modules

  frontend:
    container_name: frontend
    build:
      context: .
      target: base
      dockerfile: ./frontend/Dockerfile
    command: sh -c "npm install && npm run start"
    ports:
        - 3000:3000   
    volumes:
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    container_name: db
    image: mongo:4
    environment:
      - MONGO_DB_NAME
      - MONGO_USERNAME
      - MONGO_PASSWORD
    volumes:
      - mongodb_data:/data/db
    networks:
        - server-network
    ports:
      - "27017-27019:27017-27019"
    command: mongod --port 27017 --bind_ip_all

networks:
    server-network:
