const MISSING_VALUE = 'MISSING_VALUE'

export const AUTH0_DOMAIN = process.env.REACT_APP_AUTH0_DOMAIN || MISSING_VALUE
export const AUTH0_CLIENT_ID = process.env.REACT_APP_AUTH0_CLIENT_ID || MISSING_VALUE
